### ISSUE TITLE
What are the start/stop functions?

### ISSUE THREAD

**Issue by alexbjorlig** [alexanderschau/apollo-server-svelte-kit#4]
Why not create the server outside the handle function?

Any specific reason for using `runHttpQuery ` instead of something like `server.executeOperation`?

(just trying to understand how this works 😂 )

**Comment by alexanderschau** [comment]
> Why not create the server outside the handle function?

Because in serverless environments there's only one request before the script is killed. It also seems a bit tricky to initialize the server on a higher level.

> Any specific reason for using `runHttpQuery` instead of something like `server.executeOperation`?

Nope, I just copied from the [official implementations](https://github.com/apollographql/apollo-server/blob/bd4d6a97c8ffcbbf2ac34c2d17b573cbb511ca00/packages/apollo-server-koa/src/ApolloServer.ts#L144). With `server.executeOperation` the user would need to map the input parameters of SvelteKit to the Apollo server manually. Through this implementation you only need to point the request from SvelteKit to `apolloServer.handleRequest()`.

If you have any ideas to make things better please feel free to implement them :smile:
