### ISSUE TITLE
How do you visit the Apollo Playground?

### ISSUE THREAD

**Issue by obgibson** [alexanderschau/apollo-server-svelte-kit#5]
I have SvelteKit handling the requests correctly but I cannot work out how to visit the Apollo Playground now.  What URL should it be?  I am running on localhost:5173.

**Comment by alexanderschau** [comment]
First of all, sorry for the late response.
Sadly there is no playground anymore in version 3. Instead you should see a [landing page](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/), which tries to redirect you to a central web based playground. If this isn‘t the case, please check if your ApolloServer handler is also listening on the  `GET` method.

However my suggestion would be to use a playground browser extension, because the web based thing sometimes has some CORS problems.

Hopefully this solves your question :)
